export const baseURL =
  import.meta.env.VITE_API_BASE_URL || "http://localhost:4000";

export const apiRoutes = {
  auth: `${baseURL}/auth`,
  addUserCountry: `${baseURL}/userCountry/create`,
  getAllCountries: `${baseURL}/country/getAll`,
  updateUserPassword: "/user/updatePassword",
  getUserCountries: "/userCountry/getAll",
  getUserRecords: "/userRecord/getAll",
  getRecordPdf: "/userRecord/get/pdf",
  shareRecordPdf: "/userRecord/share/pdf",
  // Admin APi Routes
  getRecords: "/record/getAll",
  createRecord: "/record/create",
  updateRecord: "/record/edit",
  deleteRecord: "/record/delete",
  importExcel: "/record/import/excel",
  importPdf: "/record/import/pdf",
  allCountries: "/country/getAll",
  createCountry: "/country/create",
  editCountry: "/country/edit",
  deleteCountry: "/country/delete",
  getAllPendings: "/pending/getAll",
  getAllTypes: "/type/getAll",
  createType: "/type/create",
  editType: "/type/edit",
  deleteType: "/type/delete",
  getAllusers: "/user/getAll",
  createUser: "/user/create",
  editUser: "/user/edit",
  updateAdmin: "/user/updateAdmin",
  deleteUser: "/user/delete",
  acceptUser: "/pending/accept",
  rejectUser: "/pending/reject",
  settings: "/setting/site",
  openSite: "/setting/site/open",
  closeSite: "/setting/site/close",
};
